package mock

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/jo-hoe/gostwriter/internal/config"
	"github.com/jo-hoe/gostwriter/internal/llm"
)

var _ llm.Client = (*Client)(nil)
var _ llm.TitleGenerator = (*Client)(nil)

// Client is a mock LLM client that returns canned Markdown after a configurable delay.
type Client struct {
	delay  time.Duration
	prefix string
}

func New(cfg config.MockSettings) *Client {
	return &Client{
		delay:  cfg.Delay,
		prefix: cfg.Prefix,
	}
}

func (c *Client) TranscribeImage(ctx context.Context, r io.Reader, mime string) (string, error) {
	// Consume a little to simulate reading (optional)
	buf := make([]byte, 256)
	_, _ = r.Read(buf)

	// Simulate processing delay
	if c.delay > 0 {
		t := time.NewTimer(c.delay)
		defer t.Stop()
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-t.C:
		}
	}

	md := fmt.Sprintf("%s\n\nThis is a mock transcription for an image of type %q.\n\n- This output is generated by the mock LLM client.\n- Replace with a real LLM implementation later.\n", c.prefix, mime)
	return md, nil
}

// GenerateTitle satisfies llm.TitleGenerator.
// It returns the first non-empty line of markdown (stripped of leading '#') prefixed by c.prefix.
func (c *Client) GenerateTitle(ctx context.Context, markdown string) (string, error) {
	if c.delay > 0 {
		t := time.NewTimer(c.delay)
		defer t.Stop()
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-t.C:
		}
	}

	for _, line := range strings.Split(markdown, "\n") {
		line = strings.TrimSpace(strings.TrimLeft(line, "#"))
		line = strings.TrimSpace(line)
		if line != "" {
			return c.prefix + " " + line, nil
		}
	}
	return c.prefix + " Untitled", nil
}
